name: Pull Docker Image from Container Registry and Run

on:
  schedule:
    - cron: "45 23 * * *"
  push:
    branches: feature/ci

jobs:
  docker:
    runs-on: ubuntu-latest
    container: docker:dind
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - name: Pull Docker Image from Docker Hub
        run: docker pull ramongss/covidbrasilbot:latest
      - name: Run Docker Container
        run: docker run -it --env TWITTER_CONSUMER_API_KEY --env TWITTER_CONSUMER_API_SECRET --env TWITTER_ACCESS_TOKEN --env TWITTER_ACCESS_TOKEN_SECRET covidbrasilbot